import { Nunito } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar";
import { ToastProvider } from "@/context/toast-provider";
import MobileMenu from "@/components/mobile-menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Nunito({ subsets: ["latin"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ToastProvider />
        <Navbar />
        <MobileMenu />
        <div className="bg-slate-50 mx-auto p-0 sm:p-4 max-w-7xl gap-2 mb-10 w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
